### ISSUE TITLE
Strict behavior support

### ISSUE THREAD

**Issue by cviktor** [hypersolutions/hypermock#6]
Hy

I think it would be a great idea to support Loose and Strict mock behavior.

Currently if there is no setup for a call the HyperMock returns a default value in the `MockProxyDispatcherHelper` but i think it would be great to support a Strict behavior, which means if there is no setup for a call, the framework will throw an Exception. 

This is particularly useful when you work with methods that return some value type like bool, or int.

If you think this is a good idea I am happy to implement it and make a pull request.

**Comment by hypersolutions** [comment]
Hi

Just to clarify, what you are asking for is a way to override the default behavior to throw an exception if no setup has been defined rather than returning a default.

How important is this issue to you? I am not able to look at it for a couple of weeks due to other commitments but I am happy to sort it out myself.

If you could post a unit test(s) to clarify the behavior, I will certainly review and add the supported implementation for you.

**Comment by cviktor** [comment]
Yes you described it well.

Here is a simple example of my original problem:

I have a class which, I want to test.

``` c#
public class A
{
	//ctor here...
	
	public string MethodToTest()
	{
		//here I wanted to check for Condition1
		if (!Condition2())
			return "OK";
		else
			return "FAIL";
	}
	public bool Condition1()
	{
		return dependency1.Foo();
	}
	public bool Condition2()
	{
		return dependency2.Bar();
	}
}
```

My problem is that if I write a unit test for the A.MethodToTest() and I use HyperMock to mock the dependencies the test will give back false positive value because the default return value of the mocked dependency2.Bar() is false.

If the HyperMock has the ability to throw exception instead of the default value, the test will fail because in the unit test I will setup only the dependency1.Foo() to return false but not the dependency2.Bar().

What I suggest is that there should be a MockBehavior property on the Mock class which is an enum with Strict and Loose values like in moq. If the behavior is Loose then the mock returns the default value like the current implementation does. If the behavior is Strict the mocked method throws an InvalidOperationException.

It would be a nice extra to create a static field to define the default MockBehavior.

As I said I am happy to implement the feature and make a pull request that you can review and accept if the implementation is good enough.

**Comment by hypersolutions** [comment]
Thanks for the details above. I shall take a look at adding a behavior to allow you to specify loose or strict mocking. It might be in the form of an alternate StrictMock class instead of the Mock class or as you have described above. I will take a look at what feels right for the API.

I will try to take a look sometime next week or possibly this weekend if I can find time.

**Comment by cviktor** [comment]
Thanks.

In the meantime I needed this behavior for my project so I implemented it. You can see it here https://github.com/cviktor/hypermock

**Comment by hypersolutions** [comment]
Thank you for taking time to add the behaviour to your fork. 

I have added strict mock behaviour partially based around for example. I feel that having it switch on and off on a mock instance may be confusing so I have allowed you to create either a loose mock (the default) or a strict mock. You simply set the MockBehavior.Strict when calling the Mock.Create methods:

`var mock = Mock.Create<IAccountService>(MockBehavior.Strict);`

Please do take a look. I have added one example test class _StrictSetupMethodTests_. If you feel this addresses the problem, I shall go ahead and complete any remaining tests and publish to NuGet.

**Comment by hypersolutions** [comment]
Oh the branch is [release-2.0.5](https://github.com/hypersolutions/hypermock/tree/release-2.0.5)

**Comment by cviktor** [comment]
Looks good. It is a good idea to set the behavior only in the Create call. The custom exception is a nice addition too.

There is a typo on the MockBehavior.Strict enum and in the default exception message template there is a ' before the template parameter, but I think this solves the problem so I am waiting for the nuget update 😄

**Comment by hypersolutions** [comment]
Release 2.0.5 is now available on NuGet. I have updated the code review comments you observed and extended the examples project. I am also going to add a section to the wiki too.

**Comment by cviktor** [comment]
Thanks for the fast reaction, and for this very helpfull framework. I think this issue is resolved so I am closing it.
