### ISSUE TITLE
Does not work in release

### ISSUE THREAD

**Issue by sudheendraas** [hypersolutions/hypermock#8]
in release mode all the test are failing in UWP test app

**Comment by hypersolutions** [comment]
Thank you for reporting the issue. Can you try the following first.

1. Before running the UWP app tests, perform a rebuild of the UWP project. I have had an issue like this before whereby switching between debug and release and running the tests does fail.
2. Ensure VS is running as admin. I would assume you are anyhow.

Give this a go first and if its still failing, update me and I will try and take a closer look in a couple of days when I have some free time.

**Comment by sudheendraas** [comment]
![image](https://cloud.githubusercontent.com/assets/29090695/26713248/3edf5d52-4789-11e7-872b-6bd8a68d77bd.png)
Thanks for reply. 
I tried both the ways you mentioned. but no luck. 
Attached the error for your reference.
I had run your total tests 111 are failing almost are related to same error(attached) Arg_NullReferenceException. in stack trace it shows different base address

**Comment by hypersolutions** [comment]
Thanks for trying. I shall take a closer look tomorrow.

**Comment by hypersolutions** [comment]
This is related to the .NET native tool chain compilation option which is enabled by default in release mode.

Given that _HyperMock_ is targeting test projects, I have disabled the option so now all the tests run in both debug and release.

Branch pr-8 contains the fix which has been migrated back to master. No _NuGet_ packages are required to be updated as it is a simple project setting change.

**Comment by sudheendraas** [comment]
Thanks it working...
